name: check-for-linter
on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install project
              run: make install

            - name: Validate files for linter
              run: make lint

            - name: Run unit tests
              run: make test

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v5.3.0
              env:
                SONAR_TOKEN: ${{secrets.PHP_PROJECT_48_SECRET}}